[workspace]
authors = ["akoen <git@koen.ca>"]
channels = ["conda-forge"]
name = "simmetrix"
platforms = ["linux-64"]

[tasks]

[pypi-dependencies]
nanobindgen = { path = "../nanobindgen", editable = true }
pysms = { path = ".", editable = true }

[dependencies]
python = "3.12.*"
nanobind = ">=2.9.2,<3"
gmsh = ">=4.13.1,<5"
