[workspace]
authors = ["akoen <git@koen.ca>"]
channels = ["conda-forge"]
name = "simmetrix"
platforms = ["linux-64"]
preview = ["pixi-build"]


[tasks]

[pypi-dependencies]
nanobindgen = { path = "../nanobindgen", editable = true }
phnx = { path = ".", editable = true }
ipykernel = ">=7.1.0, <8"

[dependencies]
python = "3.12.*"
nanobind = ">=2.9.2,<3"
gmsh = ">=4.13.1,<5"
stellarmesh = ">=1.0.1,<2"
openmc = { version = "==0.15.2", build = "dagmc_nompi*" }
nlohmann_json = ">=3.12.0,<4"
pytest = ">=8,<9"


[package]
name = "stellarmesh"
version = "2.0.1"
description = "Meshing library for nuclear workflows."

[package.build]
backend = { name = "pixi-build-python", version = "0.4.*" }

[package.host-dependencies]
setuptools = ">=61"

[package.run-dependencies]
python = "3.12.*"
nanobind = ">=2.9.2,<3"
gmsh = ">=4.13.1,<5"
