[workspace]
authors = ["akoen <git@koen.ca>"]
channels = ["conda-forge"]
name = "simmetrix"
platforms = ["linux-64"]
preview = ["pixi-build"]


[tasks]
conf = 'cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH="$CONDA_PREFIX" -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE'
build = "cmake --build build -j 8 -t install"
clean = "rm -rf build phnx/_core _deps"

[pypi-dependencies]
nanobindgen = { path = "../nanobindgen", editable = true }
phnx = { path = ".", editable = true }
ipykernel = ">=7.1.0, <8"

[dependencies]
python = "3.12.*"
nanobind = ">=2.9.2,<3"
gmsh = ">=4.13.1,<5"
stellarmesh = ">=1.0.1,<2"
openmc = { version = "==0.15.2", build = "dagmc_nompi*" }
nlohmann_json = ">=3.12.0,<4"
pytest = ">=8,<9"


[feature.docs.pypi-dependencies]
sphinx = ">=8.2.3,<9"
sphinx-github-style = ">=1.2.2,<2"
sphinx-autobuild = ">=2025.8.25,<2026"
shibuya = "==2026.1.9"
sphinx-tabs = ">=3.4.7,<4"

[feature.docs.tasks]
docs = "sphinx-build -b html docs docs/_build/html"
docs-watch = "sphinx-autobuild docs docs/_build/html"

[environments]
docs = ["docs"]


[package]
name = "stellarmesh"
version = "2.0.1"
description = "Meshing library for nuclear workflows."

[package.build]
backend = { name = "pixi-build-python", version = "0.4.*" }

[package.host-dependencies]
setuptools = ">=61"

[package.run-dependencies]
python = "3.12.*"
nanobind = ">=2.9.2,<3"
gmsh = ">=4.13.1,<5"
